name: Go

on:
  push:
    branches: [ main ]

jobs:
  common-setup:
    runs-on: ubuntu-latest
    steps:
      - run: echo setting up
      - run: echo needs codebase, so...
      - uses: actions/checkout@2
    
  task1:
    runs-on: ubuntu-latest
    needs: [common-setup]
    steps:
      - echo task 1
    
  task2:
    runs-on: ubuntu-latest
    needs: [common-setup]
    steps:
      - echo task 2
    
  task3:
    runs-on: ubuntu-latest
    needs: [task1, task2]
    steps:
      - echo task 3
    
